export interface Country {
  name: string;
  code: string;
  flag: string;
}

export const COUNTRIES: Country[] = [
  { name: 'United States', code: 'US', flag: '🇺🇸' },
  { name: 'United Kingdom', code: 'GB', flag: '🇬🇧' },
  { name: 'India', code: 'IN', flag: '🇮🇳' },
  { name: 'Canada', code: 'CA', flag: '🇨🇦' },
  { name: 'Australia', code: 'AU', flag: '🇦🇺' },
  { name: 'Germany', code: 'DE', flag: '🇩🇪' },
  { name: 'France', code: 'FR', flag: '🇫🇷' },
  { name: 'Japan', code: 'JP', flag: '🇯🇵' },
  { name: 'China', code: 'CN', flag: '🇨🇳' },
  { name: 'Brazil', code: 'BR', flag: '🇧🇷' },
  { name: 'Spain', code: 'ES', flag: '🇪🇸' },
  { name: 'Italy', code: 'IT', flag: '🇮🇹' },
  { name: 'Netherlands', code: 'NL', flag: '🇳🇱' },
  { name: 'Sweden', code: 'SE', flag: '🇸🇪' },
  { name: 'Norway', code: 'NO', flag: '🇳🇴' },
  { name: 'Switzerland', code: 'CH', flag: '🇨🇭' },
  { name: 'United Arab Emirates', code: 'AE', flag: '🇦🇪' },
  { name: 'Saudi Arabia', code: 'SA', flag: '🇸🇦' },
  { name: 'Singapore', code: 'SG', flag: '🇸🇬' },
  { name: 'South Africa', code: 'ZA', flag: '🇿🇦' },
  { name: 'Mexico', code: 'MX', flag: '🇲🇽' },
  { name: 'Argentina', code: 'AR', flag: '🇦🇷' },
  { name: 'South Korea', code: 'KR', flag: '🇰🇷' },
  { name: 'Indonesia', code: 'ID', flag: '🇮🇩' },
  { name: 'Pakistan', code: 'PK', flag: '🇵🇰' },
  { name: 'Bangladesh', code: 'BD', flag: '🇧🇩' },
  { name: 'Nigeria', code: 'NG', flag: '🇳🇬' },
  { name: 'Egypt', code: 'EG', flag: '🇪🇬' },
  { name: 'Turkey', code: 'TR', flag: '🇹🇷' },
  { name: 'Poland', code: 'PL', flag: '🇵🇱' },
  { name: 'New Zealand', code: 'NZ', flag: '🇳🇿' },
  { name: 'Ireland', code: 'IE', flag: '🇮🇪' },
  { name: 'Portugal', code: 'PT', flag: '🇵🇹' },
  { name: 'Greece', code: 'GR', flag: '🇬🇷' },
  { name: 'Thailand', code: 'TH', flag: '🇹🇭' },
  { name: 'Malaysia', code: 'MY', flag: '🇲🇾' },
  { name: 'Philippines', code: 'PH', flag: '🇵🇭' },
  { name: 'Vietnam', code: 'VN', flag: '🇻🇳' },
  { name: 'Kenya', code: 'KE', flag: '🇰🇪' },
  { name: 'Morocco', code: 'MA', flag: '🇲🇦' },
  { name: 'Belgium', code: 'BE', flag: '🇧🇪' },
  { name: 'Austria', code: 'AT', flag: '🇦🇹' },
  { name: 'Denmark', code: 'DK', flag: '🇩🇰' },
  { name: 'Finland', code: 'FI', flag: '🇫🇮' },
  { name: 'Czech Republic', code: 'CZ', flag: '🇨🇿' },
  { name: 'Romania', code: 'RO', flag: '🇷🇴' },
  { name: 'Colombia', code: 'CO', flag: '🇨🇴' },
  { name: 'Chile', code: 'CL', flag: '🇨🇱' },
  { name: 'Peru', code: 'PE', flag: '🇵🇪' },
  { name: 'Qatar', code: 'QA', flag: '🇶🇦' },
];
